repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    # Attempts to load all TOML files to verify syntax.
    - id: check-toml
    # Attempts to load all yaml files to verify syntax.
    - id: check-yaml
      # Attempts to load all json files to verify syntax.
    - id: check-json
      # Makes sure files end in a newline and only a newline.
    - id: end-of-file-fixer
      # Trims trailing whitespace.
    - id: trailing-whitespace
      # preserve Markdown hard linebreaks
      args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix, --config, ruff.toml]
    # Run the formatter.
    - id: ruff-format
